IBM-Blockchain/ansible-collection

- .gitignore
- galaxy.yml
- roles/endorsing_organization/meta/main.yml
- roles/ordering_organization/meta/main.yml
> Add/update Galaxy metadata (resolves #66)

- plugins/modules/certificate_authority.py
- plugins/modules/external_ordering_service.py
- plugins/modules/external_organization.py
- plugins/modules/ordering_service.py
- plugins/modules/peer.py
> Fix problems with existing module documentation (contributes to #67)

- plugins/modules/certificate_authority.py
- plugins/modules/certificate_authority_info.py
- plugins/modules/enrolled_identity.py
- plugins/modules/enrolled_identity_info.py
- plugins/modules/peer.py
- plugins/modules/peer_info.py
> Make all modules return objects where applicable (resolves #74)

- roles/endorsing_organization/tasks/create.yml
- roles/ordering_organization/tasks/create.yml
- tutorial/05-add-organization-to-consortium.yml
> Fix broken roles and adding organization to consortium (resolves #79)

- plugins/module_utils/certificate_authorities.py
- plugins/module_utils/consoles.py
- plugins/module_utils/ordering_services.py
- plugins/module_utils/peers.py
- plugins/modules/external_ordering_service.py
- plugins/modules/external_organization.py
- plugins/modules/organization.py
> Use urllib.parse.join for building URLs (resolves #78)

- tutorial/97-delete-endorsing-organization-components.yml
- tutorial/98-delete-endorsing-organization-components.yml
- tutorial/99-delete-ordering-organization-components.yml
- tutorial/README.md
- tutorial/org2-vars.yml
- tutorial/tutorial.sh
> Add playbooks for deleting components (resolves #82)

- plugins/module_utils/consoles.py
- plugins/modules/certificate_authority.py
- plugins/modules/ordering_service.py
- plugins/modules/peer.py
> Ignore resource/storage configuration for free IKS clusters (resolves #84)

- plugins/modules/certificate_authority.py
- plugins/modules/ordering_service.py
- plugins/modules/peer.py
> Fix creation of components on free IKS clusters (resolves #84)

- plugins/modules/external_ordering_service.py
> Delete and re-import external ordering service on update (resolves #87)

- galaxy.yml
- tutorial/08-create-channel.yml
> Check if channel exists before creating channel (resolves #94)

- azure-pipelines.yml
- galaxy.yml
> Add Azure Pipelines configuration (contributes to #69)

- azure-pipelines.yml
> Add missing flake8 dependency (contributes to #69)

- plugins/modules/certificate_authority.py
> Support HSM in certificate authority module (contributes to #23)

- tutorial/08-create-channel.yml
> Fix error handling in create channel step (resolves #103)

- plugins/modules/peer.py
> Support HSM in peer module (contributes to #24)

- plugins/modules/ordering_service.py
> Support HSM in ordering service module (contributes to #25)

- tutorial/08-create-channel.yml
> Fix error handling again in create channel step (resolves #103)

- plugins/module_utils/consoles.py
> Retry HTTP 502/503/504 errors from console (resolves #98)

- galaxy.yml
> Bump version to v0.0.6

- .gitignore
- azure-pipelines.yml
- docs/Makefile
- docs/source/conf.py
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/modules.rst
- docs/templates/module.rst.j2
> Initial drop of documentation (contributes to #67)

- azure-pipelines.yml
- galaxy.yml
> Automate documentation publishing (contributes to #67)

- azure-pipelines.yml
> Fix documentation publishing (contributes to #67)

- azure-pipelines.yml
- docs/Makefile
> Add .nojekyll file and re-enable Ansible Galaxy publishing (contributes to #67)

- README.md
- galaxy.yml
> Add documentation to the README.md (resolves #67)

- docker/Dockerfile
- docs/source/installation.rst
> Add sample Dockerfile and documentation for using it (resolves #115)

- plugins/module_utils/fabric_utils.py
- plugins/module_utils/ordering_services.py
- plugins/module_utils/peers.py
- plugins/modules/channel_config.py
> Specify FABRIC_CFG_PATH internally so users don't have to (resolves #96)

- galaxy.yml
> Add missing URLs to Galaxy metadata (resolves #119)

- roles/endorsing_organization/tasks/create.yml
- roles/ordering_organization/tasks/create.yml
> Allow user to specify wait_timeout for roles (resolves #121)

- docs/source/index.rst
- docs/source/roles.rst
- docs/source/roles/endorsing_organization.rst
- docs/source/roles/ordering_organization.rst
> Add documentation for both roles (resolves #123)

- galaxy.yml
> Bump version to v0.0.10

- roles/console/meta/main.yml
> Add missing metadata for console role (contributes to #125, #126)

- roles/endorsing_organization/tasks/create.yml
- roles/ordering_organization/tasks/create.yml
> Remove all debug printing from all roles (resolves #131)

- docker/Dockerfile
> Add missing Fabric v1.4.6 binaries to Dockerfile (resolves #144)

- galaxy.yml
> Bump version to v0.0.11

- docker/Dockerfile
- docs/source/installation.rst
- galaxy.yml
> Add openshift module to requirements (resolves #132)

- roles/endorsing_organization/tasks/create.yml
- roles/ordering_organization/tasks/create.yml
> Ensure created organizations have a single admin (contributes to #146)

- plugins/module_utils/utils.py
> Ensure entity references passed as objects are handled correctly (resolves #155)

- plugins/modules/external_organization.py
- plugins/modules/organization.py
- plugins/modules/organization_info.py
> Add missing msp_id property to documentation (resolves #150)

- docs/source/roles/console.rst
- roles/console/defaults/main.yml
- roles/console/tasks/k8s/create.yml
- roles/console/tasks/openshift/create.yml
- roles/console/templates/k8s/operator.yml.j2
- roles/console/templates/openshift/operator.yml.j2
> Update operator image tag to 20200416, implement fix pack install (resolves #162)

- docs/source/roles/ordering_organization.rst
- roles/ordering_organization/defaults/main.yml
- roles/ordering_organization/tasks/create.yml
- roles/ordering_organization/tasks/delete.yml
- tutorial/01-create-ordering-organization-components.yml
> Expose number of ordering service nodes through role (resolves #158)

- galaxy.yml
> Bump version to v0.0.13

- docs/source/roles/endorsing_organization.rst
- roles/endorsing_organization/defaults/main.yml
- roles/endorsing_organization/tasks/create.yml
> Expose state database for peer via role (resolves #172)

- plugins/module_utils/consoles.py
- plugins/module_utils/msp_utils.py
- plugins/module_utils/organizations.py
- plugins/modules/external_organization.py
- plugins/modules/organization.py
> Add support for organizational unit identifiers (resolves #174)

- plugins/modules/external_ordering_service.py
> Delete the correct ordering service node (resolves #182)

- docs/source/index.rst
- docs/source/tutorials/installing.rst
> Add installation tutorial (resolves #184)

- galaxy.yml
> Bump version to v0.0.14

- roles/console/tasks/k8s/create.yml
- roles/console/tasks/openshift/create.yml
> Wait for console deployment to exist (resolves #190)

- plugins/module_utils/certificate_authorities.py
- plugins/modules/enrolled_identity.py
> Check enrolled identities to ensure they are still valid (resolves #193)

- plugins/modules/organization.py
> Set NodeOU certificates when not set (resolves #195)

- galaxy.yml
> Bump version to v0.0.16

- README.md
- docs/source/tutorials/installing.rst
- plugins/module_utils/cert_utils.py
- plugins/modules/organization.py
> Correctly split root/intermediate certificates in chain (resolves #175)

- plugins/modules/peer.py
> Allow Kubernetes zone to be specified for peer (contributes to #27)

- tutorial/README.md
- tutorial/ordering-org-vars.yml
- tutorial/org1-vars.yml
- tutorial/org2-vars.yml
> Extend default timeout to 10 minutes, improve tutorial (resolves #202)

- docs/source/roles/endorsing_organization.rst
- roles/endorsing_organization/defaults/main.yml
- roles/endorsing_organization/tasks/create.yml
- roles/endorsing_organization/tasks/delete.yml
> Add peer_name property for endorsing organization role (resolves #160)

- docker/Dockerfile
> Add bash to the sample Docker image (resolves #214)

- tutorial/14-add-organization-to-channel.yml
> Remove 'system' from task name (resolves #216)

- docs/source/roles/endorsing_organization.rst
- plugins/module_utils/consoles.py
- plugins/modules/certificate_authority.py
- plugins/modules/ordering_service.py
- plugins/modules/peer.py
- roles/endorsing_organization/defaults/main.yml
- roles/endorsing_organization/tasks/create.yml
- roles/endorsing_organization/tasks/delete.yml
> Add peers parameter to endorsing organization role (resolves #161)

- plugins/module_utils/consoles.py
- plugins/modules/external_ordering_service.py
> Individually remove imported ordering service nodes (resolves #219)

- docs/source/conf.py
- docs/source/installation.rst
> Improve installation instructions (resolves #221)

- docs/source/index.rst
- docs/source/tutorials/building.rst
- galaxy.yml
- tutorial/build_network.sh
> Add new build a network tutorial (contributes to #223)

- roles/console/README.md
- roles/endorsing_organization/README.md
- roles/ordering_organization/README.md
> Add README.md files for roles

- docs/source/index.rst
- docs/source/tutorials/building.rst
- docs/source/tutorials/joining.rst
- tutorial/join_network.sh
> Add new join a network tutorial (contributes to #223)

- docs/source/index.rst
- docs/source/tutorials/deploying.rst
- galaxy.yml
- tutorial/deploy_smart_contract.sh
> Add new deploy a smart contract tutorial (contributes to #223)

- galaxy.yml
> Bump version to v0.0.21

- roles/endorsing_organization/tasks/create.yml
- roles/ordering_organization/tasks/create.yml
> Separate identity registration from CA creation (contributes to #235)

- azure-pipelines.yml
- tutorial/01-create-ordering-organization-components.yml
- tutorial/02-create-endorsing-organization-components.yml
- tutorial/04-import-organization.yml
- tutorial/07-import-ordering-service.yml
- tutorial/11-create-endorsing-organization-components.yml
- tutorial/13-import-organization.yml
- tutorial/15-import-ordering-service.yml
> Lint tutorial playbooks (resolves #236)

- tutorial/97-delete-endorsing-organization-components.yml
- tutorial/98-delete-endorsing-organization-components.yml
- tutorial/99-delete-ordering-organization-components.yml
- tutorial/build_network.sh
- tutorial/join_network.sh
- tutorial/tutorial.sh
> Remove imported components when network destroyed (resolves #232)

- plugins/modules/certificate_authority.py
- roles/endorsing_organization/tasks/create.yml
- roles/ordering_organization/tasks/create.yml
> Document root vs TLS CA and duplicate API behaviour (resolves #235)

- tutorial/01-create-ordering-organization-components.yml
- tutorial/02-create-endorsing-organization-components.yml
- tutorial/11-create-endorsing-organization-components.yml
- tutorial/18-install-chaincode.yml
- tutorial/19-install-chaincode.yml
- tutorial/20-instantiate-chaincode.yml
- tutorial/21-register-application.yml
- tutorial/22-register-application.yml
- tutorial/97-delete-endorsing-organization-components.yml
- tutorial/98-delete-endorsing-organization-components.yml
- tutorial/common-vars.yml
- tutorial/org1-vars.yml
Signed-off-by: m-g-k <mgk@uk.ibm.com>
> Minor fixes for tutorial names

- plugins/module_utils/cert_utils.py
- plugins/module_utils/certificate_authorities.py
- plugins/modules/organization.py
- roles/endorsing_organization/tasks/create.yml
- roles/ordering_organization/tasks/create.yml
> Extend organization module to generate CRL from CA (contributes to #179)

- docs/source/roles/console.rst
- roles/console/defaults/main.yml
> Update default version to 2.1.3-20200520 (resolves #254)

- plugins/module_utils/module.py
```
TASK [Import the ordering service] ***********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: [Errno 2] No such file or directory: 'peer'
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "peer version", "msg": "Failed to execute the required binary (peer) on Simons-MacBook-Pro-2.local. See https://ibm-blockchain.github.io/ansible-collection/installation.html#requirements for more info. Please read module documentation and install in the appropriate location. If the required binary is installed, then the install directory may not be present …
```
> Handle missing binary errors (resolves #262)

- docs/source/roles/console.rst
- roles/console/defaults/main.yml
- roles/console/templates/k8s/console.yml.j2
- roles/console/templates/openshift/console.yml.j2
> Extend console role so you can specify zones (resolves #249)

- docs/source/conf.py
- docs/source/roles/console.rst
- docs/source/roles/endorsing_organization.rst
- docs/source/roles/ordering_organization.rst
- docs/templates/module.rst.j2
- plugins/modules/certificate_authority.py
- plugins/modules/certificate_authority_info.py
- plugins/modules/channel_block.py
- plugins/modules/channel_config.py
- plugins/modules/channel_member.py
- plugins/modules/connection_profile.py
- plugins/modules/consortium_member.py
- plugins/modules/enrolled_identity.py
- plugins/modules/external_ordering_service.py
- plugins/modules/external_organization.py
- plugins/modules/installed_chaincode.py
- plugins/modules/instantiated_chaincode.py
- plugins/modules/ordering_service.py
- plugins/modules/ordering_service_admin.py
- plugins/modules/ordering_service_info.py
- plugins/modules/organization.py
- plugins/modules/organization_info.py
- plugins/modules/peer.py
- plugins/modules/peer_channel.py
- plugins/modules/peer_info.py
- plugins/modules/registered_identity.py
Lots and lots of changes to the reference material for modules and roles.
> Big docs PR

- docs/source/tutorials/building.rst
- docs/source/tutorials/deploying.rst
- docs/source/tutorials/joining.rst
> Fix mismatch with GitHub structure (resolves #276)

- docker/Dockerfile
- docs/source/installation.rst
- galaxy.yml
- plugins/module_utils/certificate_authorities.py
- plugins/module_utils/enrolled_identities.py
- plugins/module_utils/module.py
- plugins/module_utils/msp_utils.py
- plugins/module_utils/ordering_services.py
- plugins/module_utils/peers.py
- plugins/module_utils/pkcs11/crypto.py
- plugins/modules/channel_block.py
- plugins/modules/channel_config.py
- plugins/modules/enrolled_identity.py
- plugins/modules/enrolled_identity_info.py
- plugins/modules/installed_chaincode.py
- plugins/modules/instantiated_chaincode.py
- plugins/modules/organization.py
- plugins/modules/peer_channel.py
- plugins/modules/registered_identity.py
> Support storing enrolled identities in an HSM (resolves #279)

- docker/Dockerfile
> Use Red Hat Universal Base Image instead of Alpine (resolves #281)

- tutorial/05-add-organization-to-consortium.yml
- tutorial/10-add-anchor-peer-to-channel.yml
- tutorial/14-add-organization-to-channel.yml
- tutorial/17-add-anchor-peer-to-channel.yml
> Remove unused parameters from tutorial (resolves #283)

- docker/Dockerfile
- galaxy.yml
> Build HSM enabled Fabric binaries in Docker image (resolves #285)

- plugins/module_utils/pkcs11/crypto.py
> Fix Crypto error when imports are missing (resolves #287)

- plugins/modules/registered_identity.py
> Handle registered identity with nil attributes (resolves #291)

- docker/Dockerfile
> Reinstall collection if Galaxy metadata changes (resolves #293)

- plugins/module_utils/cert_utils.py
- plugins/module_utils/consoles.py
- plugins/modules/ordering_service.py
- plugins/modules/peer.py
Resolves #19
Resolves #20
Resolves #21
Resolves #22
> Enable peer and ordering_service modules to update admin certs

- plugins/modules/certificate_authority.py
> Support configuring replicas for certificate authority (resolves #26)

- plugins/modules/certificate_authority.py
> Add version parameter to certificate authority module (resolves #29)

- plugins/modules/peer.py
> Add version parameter to peer module (resolves #30)

- plugins/modules/ordering_service.py
> Add version parameter to ordering service module (resolves #31)

- roles/console/defaults/main.yml
- roles/console/templates/k8s/console.yml.j2
- roles/console/templates/k8s/operator.yml.j2
- roles/console/templates/openshift/console.yml.j2
- roles/console/templates/openshift/operator.yml.j2
> Enable full control over images and tags (contributes to #295)

- galaxy.yml
> Bump to v0.0.29

- roles/crds/templates/ibpca-crd.yml.j2
- roles/crds/templates/ibpconsole-crd.yml.j2
- roles/crds/templates/ibporderer-crd.yml.j2
- roles/crds/templates/ibppeer-crd.yml.j2
> Update custom resource definitions (contributes to #295)

- plugins/modules/ordering_service.py
> Rename zone to zones for ordering service module (resolves #303)

- azure-pipelines.yml
- galaxy.yml
> Configure IBM Cloud connection (contributes to #71)

- azure-pipelines.yml
> Add missing account and region arguments (contributes to #71)

- .gitignore
- azure-pipelines.yml
- tests/integration/integration_config.yml
- tests/integration/targets/certificate_authority/tasks/assertions.yml
- tests/integration/targets/certificate_authority/tasks/main.yml
> First integration test (contributes to #71)

- azure-pipelines.yml
> Fix current directory for running tests (contributes to #71)

- plugins/module_utils/consoles.py
> Fix error handling for retries (resolves #318)

- tests/integration/targets/certificate_authority/tasks/assertions.yml
> Fix integration tests

- docs/source/roles/crds.rst
- roles/crds/defaults/main.yml
- roles/crds/tasks/openshift/create.yml
- roles/crds/tasks/openshift/delete.yml
- roles/crds/templates/openshift/security_context_constraints.yml.j2
> Create security context constraints for webhook (resolves #326)

- galaxy.yml
> Bump to v0.0.32

- plugins/modules/channel_capabilities.py
> Add new channel capabilities module (resolves #341)

- plugins/module_utils/peers.py
- plugins/modules/approved_chaincode.py
- plugins/modules/installed_chaincode.py
> Add new approved chaincode module (resolves #343)

- plugins/module_utils/peers.py
- plugins/modules/committed_chaincode.py
> Add new committed chaincode module (resolves #344)

- plugins/modules/channel_parameters.py
> Add new channel parameters module (contributes to #274)

- galaxy.yml
- plugins/module_utils/peers.py
> Handle potentially missing 'Input:' from output (resolves #374)

- plugins/modules/ordering_service.py
- plugins/modules/peer.py
> Look for admin certs in all three possible locations (resolves #376)

- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
> Set default version to 2.5.0-20200714 (resolves #378)

- plugins/module_utils/consoles.py
> Do a case-insensitive search for console users (resolves #386)

- galaxy.yml
> Bump to v0.0.35

- plugins/module_utils/msp_utils.py
- plugins/modules/consortium_member_info.py
> Add new consortium member info module (resolves #391)

- plugins/modules/channel_member_info.py
> Add new channel member info module (resolves #392)

- plugins/modules/ordering_service_node_info.py
> Add new ordering service node info module (resolves #365)

- plugins/module_utils/consoles.py
- plugins/module_utils/ordering_services.py
- plugins/modules/external_ordering_service.py
- plugins/modules/ordering_service.py
- plugins/modules/ordering_service_info.py
- plugins/modules/ordering_service_node_info.py
> Expose the consenter_proposal_fin property (contributes to #362)

- galaxy.yml
> Bump to v0.0.36

- plugins/module_utils/consoles.py
- plugins/module_utils/peers.py
- plugins/modules/ordering_service_node.py
- plugins/modules/peer.py
- plugins/modules/peer_info.py
> Sort out pem vs tls_ca_root_cert vs tls_cert for peers (resolves #399)

- plugins/module_utils/consoles.py
> Respect Retry-After header when console returns HTTP 429 (resolves #189)

- plugins/module_utils/consoles.py
- plugins/module_utils/utils.py
> Handle but warn about a console with only /v1 APIs (resolves #418)

- galaxy.yml
> Bump to v0.0.39

- plugins/module_utils/consoles.py
> Check the right thing for v1 (resolves #425)

- .ansible-lint
- azure-pipelines.yml
- plugins/module_utils/peers.py
> Fix error messages (resolves #429)

- plugins/modules/connection_profile.py
> TLS CA certificates for CA should be array (resolves #432)

- roles/console/tasks/k8s/delete.yml
- roles/console/tasks/openshift/delete.yml
> Use correct API version for deleting console (resolves #431)

- docker/Dockerfile
- docker/docker-entrypoint.sh
> Use root group writable directories and set USER to 7051 (resolves #438)

- roles/console/templates/k8s/cluster_role.yml.j2
- roles/console/templates/openshift/cluster_role.yml.j2
Signed-off-by: Jake Turner <10009752+Jakeeyturner@users.noreply.github.com>
> Added jobs resource

- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
> Set default version to 2.5.0-20200825 (resolves #442)

- galaxy.yml
> Bump version to v0.0.42

- Dockerfile
- azure-pipelines.yml
- galaxy.yml
> Automatically publish Docker image on release (resolves #440)

- docs/source/installation.rst
- docs/source/tutorials/building.rst
- docs/source/tutorials/deploying.rst
- docs/source/tutorials/joining.rst
> Update documentation to use published Docker image (contributes to #440)

- .dockerignore
- galaxy.yml
- plugins/module_utils/ordering_services.py
- plugins/modules/channel_block.py
- plugins/modules/channel_config.py
> Expose FAB-18205 through Ansible collection (resolves #449)

- roles/console/tasks/k8s/delete.yml
- roles/console/tasks/openshift/delete.yml
> Check CRDs exist before attempting to delete console (resolves #452)

- roles/console/defaults/main.yml
- roles/console/tasks/create.yml
- roles/console/tasks/k8s/create.yml
- roles/console/tasks/k8s/delete.yml
- roles/console/tasks/openshift/create.yml
- roles/console/tasks/openshift/delete.yml
- roles/crds/defaults/main.yml
- roles/crds/tasks/create.yml
- roles/crds/tasks/k8s/create.yml
- roles/crds/tasks/k8s/delete.yml
- roles/crds/tasks/openshift/create.yml
- roles/crds/tasks/openshift/delete.yml
> Verify parameters are defined and are not empty (resolves #436)

- galaxy.yml
> Bump version to v0.0.45

- azure-pipelines.yml
> Automatically run HCL AppScan on Cloud

- Dockerfile
- azure-pipelines.yml
- docker/Dockerfile
- galaxy.yml
- plugins/modules/certificate_authority.py
- plugins/modules/ordering_service.py
- plugins/modules/ordering_service_node.py
- plugins/modules/peer.py
> Make pkcs11endpoint parameter optional (resolves #460)

- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- galaxy.yml
- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
> Set default version to 2.5.0-20201001 (resolves #464)

- roles/console/templates/k8s/console.yml.j2
- roles/console/templates/openshift/console.yml.j2
- roles/crds/templates/ibpca-crd.yml.j2
- roles/crds/templates/ibpconsole-crd.yml.j2
- roles/crds/templates/ibporderer-crd.yml.j2
- roles/crds/templates/ibppeer-crd.yml.j2
> Support new v1beta1 version in IBP 2.5.1 (resolves #466)

- galaxy.yml
- plugins/modules/certificate_authority.py
- plugins/modules/ordering_service.py
- plugins/modules/ordering_service_node.py
- plugins/modules/peer.py
> Use console default for storage class when not specified (resolves #468)

- roles/crds/templates/ibpca-crd.yml.j2
- roles/crds/templates/ibpconsole-crd.yml.j2
- roles/crds/templates/ibporderer-crd.yml.j2
- roles/crds/templates/ibppeer-crd.yml.j2
- tests/integration/targets/it_certificate_authority/tasks/assertions.yml
- tests/integration/targets/it_certificate_authority/tasks/main.yml
> Specify correct namespace in CRDs (resolves #471)

- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- galaxy.yml
- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
> Set default version to 2.5.1-20201030 (resolves #473)

- azure-pipelines.yml
- docker/Dockerfile
- docs/source/installation.rst
- docs/source/tasks/enable-fabricv2-capability.rst
- docs/source/tasks/update-channel-parameters.rst
- plugins/module_utils/consoles.py
- plugins/modules/certificate_authority.py
- plugins/modules/ordering_service.py
- plugins/modules/ordering_service_node.py
- plugins/modules/peer.py
- tutorial/v2.x/common-vars.yml
> Add semantic version range specification support (resolves #475)

- azure-pipelines.yml
- azure-templates/build-dependencies.yml
- azure-templates/integration-tests.yml
- azure-templates/test-dependencies.yml
- azure-templates/tutorial-tests.yml
- galaxy.yml
> Extend overnight testing to include SaaS + Docker + tutorial

- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
> Set default version to 2.5.1-20201119

- azure-pipelines.yml
> Fix the release process

- galaxy.yml
> Bump version to v0.0.53

- azure-templates/test-dependencies.yml
- docs/source/roles/endorsing_organization.rst
- docs/source/roles/ordering_organization.rst
- plugins/module_utils/consoles.py
- roles/endorsing_organization/defaults/main.yml
- roles/endorsing_organization/tasks/create.yml
- roles/endorsing_organization/tasks/delete.yml
- roles/ordering_organization/defaults/main.yml
- roles/ordering_organization/tasks/create.yml
- roles/ordering_organization/tasks/delete.yml
> Permit control over wallet/identity paths for roles (resolves #488)

- galaxy.yml
> Bump version to v0.0.54

- plugins/module_utils/consoles.py
> Catch and retry SSLError exceptions (contributes to #437)

- plugins/module_utils/consoles.py
> Catch and retry errors based on text (contributes to #437)

- plugins/module_utils/msp_utils.py
- plugins/modules/channel_member.py
- plugins/modules/consortium_member.py
- plugins/modules/ordering_service_admin.py
> Allow users to override per-organization policies (resolves #493)

- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- galaxy.yml
- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
> Set default version to 2.5.1-20201208

- plugins/module_utils/consoles.py
> Perform version upgrade in its own request, if required (resolves #496)

- galaxy.yml
> Bump version to v0.0.56

- galaxy.yml
- roles/mzha_ordering_organization/README.md
- roles/mzha_ordering_organization/defaults/main.yml
- roles/mzha_ordering_organization/meta/main.yml
- roles/mzha_ordering_organization/tasks/create.yml
- roles/mzha_ordering_organization/tasks/delete.yml
- roles/mzha_ordering_organization/tasks/main.yml
> Introduce new mzha_ordering_organization role (contributes to #499)

- plugins/module_utils/consoles.py
- plugins/modules/channel_consenter.py
- plugins/modules/external_certificate_authority.py
- plugins/modules/external_ordering_service_node.py
- plugins/modules/ordering_service_node.py
- roles/mrha_ordering_organization/README.md
- roles/mrha_ordering_organization/defaults/main.yml
- roles/mrha_ordering_organization/meta/main.yml
- roles/mrha_ordering_organization/tasks/create.yml
- roles/mrha_ordering_organization/tasks/create/primary-osn.yml
- roles/mrha_ordering_organization/tasks/create/primary-region.yml
- roles/mrha_ordering_organization/tasks/create/secondary-osn.yml
- roles/mrha_ordering_organization/tasks/create/secondary-region.yml
- roles/mrha_ordering_organization/tasks/delete.yml
- roles/mrha_ordering_organization/tasks/delete/primary-osn.yml
- roles/mrha_ordering_organization/tasks/delete/primary-region.yml
- roles/mrha_ordering_organization/tasks/delete/secondary-osn.yml
- roles/mrha_ordering_organization/tasks/delete/secondary-region.yml
- roles/mrha_ordering_organization/tasks/main.yml
Also introduces new modules that were required to implement this role:
- channel_consenter
- external_certificate_authority
- external_ordering_service_node
> Introduce new mrha_ordering_organization role (contributes to #502)

- plugins/modules/channel_policy.py
> Replace policy, don't merge it with existing policy (resolves #507)

- roles/mzha_endorsing_organization/README.md
- roles/mzha_endorsing_organization/defaults/main.yml
- roles/mzha_endorsing_organization/meta/main.yml
- roles/mzha_endorsing_organization/tasks/create.yml
- roles/mzha_endorsing_organization/tasks/delete.yml
- roles/mzha_endorsing_organization/tasks/main.yml
> Introduce new mzha_endorsing_organization role (contributes to #501)

- plugins/module_utils/consoles.py
- plugins/modules/external_peer.py
- roles/mrha_endorsing_organization/README.md
- roles/mrha_endorsing_organization/defaults/main.yml
- roles/mrha_endorsing_organization/meta/main.yml
- roles/mrha_endorsing_organization/tasks/create.yml
- roles/mrha_endorsing_organization/tasks/create/primary-peer.yml
- roles/mrha_endorsing_organization/tasks/create/primary-region.yml
- roles/mrha_endorsing_organization/tasks/create/secondary-peer.yml
- roles/mrha_endorsing_organization/tasks/create/secondary-region.yml
- roles/mrha_endorsing_organization/tasks/delete.yml
- roles/mrha_endorsing_organization/tasks/delete/primary-peer.yml
- roles/mrha_endorsing_organization/tasks/delete/primary-region.yml
- roles/mrha_endorsing_organization/tasks/delete/secondary-peer.yml
- roles/mrha_endorsing_organization/tasks/delete/secondary-region.yml
- roles/mrha_endorsing_organization/tasks/main.yml
Also introduces new modules that were required to implement this role:
- external_peer
> Introduce new mrha_endorsing_organization role (contributes to #503)

- galaxy.yml
> Bump to v0.0.58

- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- galaxy.yml
- plugins/module_utils/consoles.py
- plugins/modules/certificate_authority.py
- plugins/modules/ordering_service.py
- plugins/modules/ordering_service_node.py
- plugins/modules/peer.py
- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
- roles/mrha_ordering_organization/tasks/delete/primary-region.yml
> Bump version to 2.5.1-20210112

- plugins/module_utils/certificate_authorities.py
> Retry certificate authority operations (contributes to #437)

- docs/source/roles/mrha_endorsing_organization.rst
- galaxy.yml
- plugins/module_utils/consoles.py
> Fix documentation for mrha_endorsing_organization role

- .ansible-lint
- .yamllint.yml
- azure-pipelines.yml
- plugins/module_utils/certificate_authorities.py
- plugins/module_utils/consoles.py
- plugins/module_utils/ordering_services.py
- plugins/module_utils/peers.py
- roles/console/tasks/k8s/create.yml
- roles/console/tasks/openshift/create.yml
- tests/integration/targets/it_certificate_authority/tasks/assertions.yml
- tests/integration/targets/it_external_ordering_service/tasks/main.yml
> Add sleeps between retries

- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
> Bump IBP version to 2.5.1-20210222

- galaxy.yml
> Bump version to v1.0.2

- Dockerfile
- azure-pipelines.yml
- azure-templates/build-dependencies.yml
- azure-templates/test-dependencies.yml
- docs/source/installation.rst
> Pin OpenShift dependency to 0.11.2

- .github/workflows/main.yml
- galaxy.yml
> Move to GitHub Actions

- .github/workflows/main.yml
> Fix Docker usage for tutorial tests

- .github/scripts/run-integration-tests.sh
- .github/workflows/main.yml
> Integration tests not running

- .github/scripts/purge.sh
- .github/workflows/purge.yml
> Add workflow to purge all lost components

- .github/scripts/bump.sh
- .github/workflows/main.yml
- galaxy.yml
> Fix documentation publishing, add version bump

- .github/workflows/main.yml
- plugins/module_utils/certificate_authorities.py
- plugins/modules/organization.py
> Retry connection errors retrieving CA chain

- plugins/module_utils/consoles.py
- plugins/module_utils/utils.py
- plugins/modules/certificate_authority.py
- plugins/modules/external_certificate_authority.py
- plugins/modules/external_ordering_service.py
- plugins/modules/external_ordering_service_node.py
- plugins/modules/external_organization.py
- plugins/modules/external_peer.py
- plugins/modules/ordering_service.py
- plugins/modules/ordering_service_node.py
- plugins/modules/organization.py
- plugins/modules/peer.py
> Ensure that lookups by name use required type

- .github/workflows/main.yml
- galaxy.yml
- plugins/module_utils/certificate_authorities.py
- plugins/module_utils/consoles.py
- plugins/module_utils/ordering_services.py
- plugins/module_utils/peers.py
> Increase time inbetween retries

- Dockerfile
- galaxy.yml
- requirements.txt
> Switch to Ansible 2.10 (contributes to #538)

- galaxy.yml
> Add dependency on community.kubernetes collection

- .github/workflows/main.yml
- docs/source/conf.py
- docs/source/installation.rst
- docs/source/roles/console.rst
- docs/source/roles/crds.rst
- docs/source/roles/endorsing_organization.rst
- docs/source/roles/mrha_endorsing_organization.rst
- docs/source/roles/mrha_ordering_organization.rst
- docs/source/roles/mzha_endorsing_organization.rst
- docs/source/roles/mzha_ordering_organization.rst
- docs/source/roles/ordering_organization.rst
- docs/source/tasks/addadmincert.rst
- docs/source/tasks/enable-fabricv2-capability.rst
- docs/source/tasks/haca.rst
- docs/source/tasks/update-channel-parameters.rst
- docs/source/tutorials/building.rst
- docs/source/tutorials/deploying.rst
- docs/source/tutorials/joining.rst
- docs/templates/module.rst.j2
> Rename master branch to main

- plugins/module_utils/certificate_authorities.py
- plugins/modules/enrolled_identity.py
Add new `tls` option. When `tls` is set to `true`, enroll
against the TLS certificate authority. You cannot use this
option and a PKCS #11 compliant HSM at the same time.
Add new `hosts` option. Can only be specified when `tls`
is set to `true`. The `hosts` option can optionally provide
a list of X.509 Subject Alternative Names, specified as
either IP addresses or DNS names.
> Allow enrolled_identity module to enroll TLS certificates

- plugins/module_utils/certificate_authorities.py
> Fix call to _enroll_ca

- .ansible-lint
- plugins/modules/enrolled_identity.py
- requirements.txt
> Add options for automatically re-enrolling identities (resolves #39)

- plugins/modules/channel_config.py
Extend the `channel_config` module so that you can specify ACLs at channel creation time.
Example usage:
```
- name: Create the configuration for a new channel
ibm.blockchain_platform.channel_config:
api_endpoint: https://ibp-console.example.org:32000
api_authtype: basic
api_key: xxxxxxxx
api_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
operation: create
name: mychannel
path: channel_config_update.bin
organizations:
- Org1
policies:
Admins: admins-policy.json
Readers: readers-policy.json
Writers: writers-policy.json
acls:
lscc/ChaincodeExists: /Channel/Application/Admins
```
> Extend channel_config module with ACL support

- plugins/modules/peer_channel.py
The `operation` parameter in the `peer_channel` module only has one option, `join`.
Remove the `operation` parameter from this module and make it like any other Ansible
module by having a `state` parameter instead. When `state` is set to `present`, ensure
that the peer is joined into the specified channel. When `state` is set to `absent`,
ensure that the peer is not joined into the specified channel.
Because peers can't currently leave a channel, attempting this will throw an error, but
this is on the Hyperledger Fabric roadmap and can be added at a later date.
These changes are compatible because any existing `operation` parameters will be ignored,
and the `state` parameter defaults to `present`, preserving existing behaviour.
> Remove operation parameter from peer_channel module (resolves #269)

- plugins/modules/channel_block.py
The `operation` parameter in the `channel_block` module only has one option, `fetch`.
Remove the `operation` parameter from this module and make it like any other Ansible
module by having a `state` parameter instead. When `state` is set to `present`, ensure
that the block is fetched from the specified channel and stored at `path`. When `state`
is set to `absent`, ensure that there is no block stored at `path`.
These changes are compatible because any existing `operation` parameters will be ignored,
and the `state` parameter defaults to `present`, preserving existing behaviour.
> Remove operation parameter from channel_block module (resolves #272)

- plugins/module_utils/module.py
> Fix logger issue

- .github/scripts/run-tests.sh
- .github/scripts/run-tutorial-tests.sh
- .github/workflows/main.yml
- docs/source/index.rst
- docs/source/support.rst
- plugins/module_utils/module.py
> Missing log collection for integration tests in CI

- .github/scripts/run-tests.sh
- .github/workflows/main.yml
> Use absolute path for logs

- .github/scripts/run-tutorial-tests.sh
> Fix logging for Docker tests

- plugins/module_utils/consoles.py
> Stop retrying IBM Cloud login on success

- galaxy.yml
> Update to 1.1.0

- roles/crds/tasks/openshift/create.yml
> Correct template names

- plugins/modules/committed_chaincode.py
> Committed Chaincode options

- roles/console/defaults/main.yml
- roles/crds/defaults/main.yml
- roles/hlfsupport_console/defaults/main.yml
- roles/hlfsupport_crds/defaults/main.yml
reference https://cloud.ibm.com/docs/blockchain-sw-252?topic=blockchain-sw-252-upgrade-k8
> Update to the most recent versions of IBP and the support offering

- CONTRIBUTING.md
- justfile
- poetry.lock
- pyproject.toml
- justfile
- poetry for python modules
- updated contrib guide
> Update the development experience

- galaxy.yml
- pyproject.toml
> Prepare v2-beta

- roles/fabric_console/defaults/main.yml
- roles/fabric_console/templates/k8s/hlf-operations-console.yaml.j2
> Allow specifing versions of the images used

- .github/workflows/publish-beta.yml
> Add workflow to publish to ghcr.io

- .github/workflows/publish-beta.yml
> ...gha... again

- roles/fabric_console/defaults/main.yml
- roles/fabric_console/templates/k8s/hlf-operations-console.yaml.j2
> Update to latest k8s peer and correct versions

- docs/source/index.rst
- docs/source/tutorials/oss-installing.rst
This PR is an initial try to document the installation of Open Source Hyperledger Fabric using the ansible collection
> Update oss hlf documentation

- Dockerfile
- poetry.lock
- pyproject.toml
> Add in the JMS query/K8s abilities

- .ansible-lint
- examples/opensource-stack/templates/ingress/kustomization.yaml
- roles/fabric_operator_crds/tasks/k8s/create.yml
- roles/fabric_operator_crds/tasks/openshift/create.yml
- roles/fabric_operator_crds/templates/k8s/ingress/kustomization.yaml
- Added rule ignore
- Fixed remaining linting issues to allow for action to run
> Ignored rule for role prefixes 
