plugins/modules/external_ordering_service.py, plugins/modules/external_organization.py, plugins/modules/ordering_service.py, plugins/modules/ordering_service_info.py, plugins/modules/organization.py, plugins/modules/organization_info.py
=> Use contains, not suboptions, in returns documentation (contributes to #67)

docs/source/roles/console.rst, docs/source/roles/endorsing_organization.rst, docs/source/roles/ordering_organization.rst, roles/console/defaults/main.yml, roles/console/tasks/create.yml, roles/console/tasks/delete.yml, roles/console/tasks/main.yml, roles/console/tasks/openshift/create.yml, roles/console/tasks/openshift/delete.yml, roles/console/templates/openshift/cluster_role.yml.j2, roles/console/templates/openshift/cluster_role_binding.yml.j2, roles/console/templates/openshift/console.yml.j2, roles/console/templates/openshift/image_pull_secret.yml.j2, roles/console/templates/openshift/operator.yml.j2, roles/console/templates/openshift/security_context_constraints.yml.j2
Example:
```
- name: Deploy IBM Blockchain Platform console
hosts: localhost
vars:
state: present
target: openshift
arch: amd64
project: sstone1-delta
image_registry_password: nothingtoseeherelol
image_registry_email: sstone1@uk.ibm.com
console_domain: apps.sstone1.os.fyre.ibm.com
console_email: sstone1@uk.ibm.com
console_default_password: nothingtoseehereeither
roles:
- ibm.blockchain_platform.console
```
=> Add console role with support for Red Hat OpenShift (contributes to #125)

docs/source/roles/console.rst, roles/console/defaults/main.yml, roles/console/tasks/k8s/create.yml, roles/console/tasks/k8s/delete.yml, roles/console/tasks/openshift/create.yml, roles/console/templates/k8s/cluster_role.yml.j2, roles/console/templates/k8s/cluster_role_binding.yml.j2, roles/console/templates/k8s/console.yml.j2, roles/console/templates/k8s/image_pull_secret.yml.j2, roles/console/templates/k8s/operator.yml.j2, roles/console/templates/k8s/pod_security_policy.yml.j2, roles/console/templates/k8s/role_binding.yml.j2
Example:
```
- name: Deploy IBM Blockchain Platform console
hosts: localhost
vars:
state: present
target: k8s
arch: amd64
namespace: sstone1-alpha
image_registry_password: nothingtoseeherelol
image_registry_email: sstone1@uk.ibm.com
console_domain: 192-168-64-28.nip.io
console_email: sstone1@uk.ibm.com
console_default_password: nothingtoseehereeither
roles:
- ibm.blockchain_platform.console
```
=> Extend console role with support for Kubernetes (contributes to #126)

plugins/modules/ordering_service.py, plugins/modules/peer.py
Align the `peer` and `ordering_service` modules with the `organization` modules by renaming `admin_certificates` to `admins`.
=> Rename admin_certificates to admins (contributes to #146)

docs/source/tutorials/building.rst, docs/source/tutorials/joining.rst
- Mention new common-vars.yml file
- Fix shell extensions (#233)
- Mention removing imported identities (#231)
=> Multiple tutorial updates (resolves #231, resolves #233)

docs/source/roles/console.rst, roles/console/templates/k8s/console.yml.j2, roles/console/templates/openshift/console.yml.j2
Allow console role to use an existing TLS secret containing existing tls.crt and tls.key.
Populates the tlsSecretName in the console.yml
=> Allow console role to use existing TLS secret

plugins/module_utils/cert_utils.py, plugins/module_utils/certificate_authorities.py, plugins/module_utils/module.py, plugins/modules/certificate_authority.py, plugins/modules/certificate_authority_info.py, plugins/modules/channel_block.py, plugins/modules/channel_config.py, plugins/modules/channel_member.py, plugins/modules/channel_policy.py, plugins/modules/connection_profile.py, plugins/modules/consortium_member.py, plugins/modules/enrolled_identity.py, plugins/modules/enrolled_identity_info.py, plugins/modules/external_ordering_service.py, plugins/modules/external_organization.py, plugins/modules/installed_chaincode.py, plugins/modules/instantiated_chaincode.py, plugins/modules/ordering_service.py, plugins/modules/ordering_service_admin.py, plugins/modules/ordering_service_info.py, plugins/modules/organization.py, plugins/modules/organization_info.py, plugins/modules/peer.py, plugins/modules/peer_channel.py, plugins/modules/peer_info.py, plugins/modules/registered_identity.py
```
TASK [Import the ordering service] ***********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: No module named 'hfc'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (fabric-sdk-py) on Simons-MacBook-Pro-2.local's Python /Users/sstone1/.pyenv/versions/3.8.1/bin/python3.8. See https://ibm-blockchain.github.io/ansible-collection/installation.html#requirements for more info. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible …
```
=> Handle missing Python module errors (resolves #260)

plugins/modules/certificate_authority.py, plugins/modules/external_ordering_service.py, plugins/modules/peer.py
=> Handle HTTP 404 Not Found errors when state == absent (resolves #253)

plugins/modules/certificate_authority.py, plugins/modules/ordering_service.py, plugins/modules/peer.py
If the version of IBM Blockchain Platform is upgraded, then the version of any existing components is no longer recognized, and sending it back to the update API results in a HTTP 500 status code. We probably don't want to send the version unless we're very sure.
=> Don't send version in if it has not changed (resolves #289)

azure-pipelines.yml, tests/integration/integration_config.yml, tests/integration/targets/certificate_authority/tasks/main.yml
=> More fixes for automated integration test (contributes to #71)

docs/source/tutorials/installing.rst, tests/integration/targets/it_ordering_organization/tasks/main.yml
In the RedHat OpenShift example, the target is incorrectly pointing to k8s when should be openshift
(kudos to @jinvanstee for the fix, cherry-picked it due to missing DCO)
=> Update installing.rst (resolves #325)

docker/Dockerfile
Allow docker build to run in ocp without errors
Previously you would get many errors of the form:
time="2020-07-31T15:19:52Z" level=error msg="Can't add file /var/lib/containers/storage/overlay/4a26cb563425c5e6d6018100bd171116608320fbc468da7ce062210f30784cc3/diff/var/cache/yum/metadata/rhel-8-for-x86_64-appstream-rpms-8-x86_64/gpgdir/S.gpg-agent to tar: archive/tar: sockets not supported"
This is caused by a problem in buildah:
containers/buildah#1888
The fix here implements the suggested workaround of adding 'microdnf clean all' to each 'microdnf install'
Signed-off-by: m-g-k <mgk@uk.ibm.com>
=> Allow docker build to run in ocp without errors

docs/source/installation.rst
Change "Python" to "Ansible" at start of first sentence in the requirements section for Ansible.
=> correct typo in requirements

Dockerfile
Issue #477 
The semantic_version dependency is no longer included in the dependency tree. Installing it as part of the image build process.
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>
=> [477] Add missing Python dependency

Dockerfile, azure-pipelines.yml, docs/source/installation.rst, docs/source/tutorials/building.rst, docs/source/tutorials/deploying.rst, docs/source/tutorials/joining.rst, galaxy.yml, tutorial/05-enable-capabilities.yml
Also, add "-u $(id -u)" flag to Docker instructions to avoid permission problems on Linux.
=> Provide Fabric v2.x binaries in Docker image

requirements.txt
=> Use fork of ansible-doc-extractor with ansible-base dependency

plugins/modules/channel_acl.py
Introduce a new Ansible module, `channel_acl`, that can be used to manage the ACLs on a Hyperledger Fabric channel.
Example usage:
```
- name: Add the ACL to the channel
ibm.blockchain_platform.channel_acl:
state: present
name: lscc/ChaincodeExists
policy: /Channel/Application/Admins
path: channel_config.bin
- name: Remove the ACL from the channel
ibm.blockchain_platform.channel_acl:
state: absent
name: lscc/ChaincodeExists
path: channel_config.bin
```
=> Add new channel_acl module

plugins/module_utils/peers.py, plugins/modules/approved_chaincode.py, plugins/modules/committed_chaincode.py
For the 'lifecycle chaincode approve/commit' calls, pass the api_timeout
property to the --waitForEventTimeout
=> fix: pass api_timeout to the peer commands

galaxy.yml, roles/console/tasks/k8s/create.yml, roles/crds/templates/ca-crd.yml.j2, roles/crds/templates/console-crd.yml.j2, roles/crds/templates/orderer-crd.yml.j2, roles/crds/templates/peer-crd.yml.j2, roles/hlfsupport_console/tasks/k8s/create.yml
Update the K8S APIs to latest versions, so 1.22 is supported
Make the version of the collection to be 1.1.2
=> Support K8S 1.22

plugins/module_utils/certificate_authorities.py, plugins/modules/enrolled_identity.py, requirements.txt
When setting 'force-reenroll' on the ansible enrolled_identity task
this would fail with an authorization error
Believe that the task was calling the wrong method on the 'fabric-ca-client'
Re-enrolling TLS created certs not supported
=> Reenrollment causes Authorisation Failure

docs/source/modules.rst, plugins/module_utils/peers.py, plugins/modules/committed_chaincode.py
- permit JSON string to be included on the committed chaincode
- add note to docs on why there are not general purposes invoke modules
=> Legacy Chaincode init

plugins/module_utils/peers.py
Update the commands that call the peer binary to not capture stderr as stdout
Instead it is routed to the log file.
Setting the fabric environment variable for debug would break as stdout was expected
to contain only JSON.
=> Update the commands that call the peer binary to not capture stderr as stdout

galaxy.yml, plugins/module_utils/dict_utils.py, roles/console/defaults/main.yml, roles/console/templates/k8s/console.yml.j2, roles/console/templates/openshift/console.yml.j2, roles/crds/defaults/main.yml, roles/crds/templates/k8s/deployment.yml.j2, roles/crds/templates/openshift/deployment.yml.j2, roles/hlfsupport_console/templates/k8s/operator.yml.j2, roles/hlfsupport_console/templates/openshift/operator.yml.j2
This brings in the very latest Hyperleder Fabric release, 2.4. This lets you
use the gateway functionality. Makes application connectivity much simpler
=> Update to support installing IBP v2.5.3

.ansible-lint, Dockerfile, docs/source/installation.rst, docs/source/migrating-v12-v2.rst, meta/runtime.yml, requirements.txt
Update to support latest ansible
1. Use the latest ansible version
2. User python3.9.
3. Change ansible-lint to ignore the warning "fqcn-builtins"
4. Update other dependencies to latest
=> Support ansible 2.13

roles/fabric_operator_crds/defaults/main.yml
This PR updates the default operator image to use the hyperledger-labs/fabric-operator.   The previous value was referencing the ibm-blockchain/fabric-operator, which was the staging ground for a transition to HLF, and is not the latest / stable operator build. 
Signed-off-by: Josh Kneubuhl <jkneubuh@us.ibm.com>
=> Change the default operator image from ibm-blockchain to hyperledger-labs

roles/fabric_console/templates/k8s/hlf-operations-console.yaml.j2
This PR enables setting a custom TLS secret to be used by the TLS termination of the console and HA deployment of Fabric to multiple zones.
Signed-off-by: Arnaud van Gelder <arnaud.van.gelder-cic.netherlands@ibm.com>
=> adding custom TLS secret and HA deployment

examples/chaincode_info/00-org1-chaincode-info.yml, plugins/module_utils/peers.py, plugins/modules/approved_chaincode.py, plugins/modules/chaincode_list_info.py
Add in new modules to get access to chaincode information from the peer.
```
{
"changed": false,
"committed_chaincodes": [
{
"collections": {},
"endorsement_plugin": "escc",
"name": "asset-transfer",
"sequence": 3,
"validation_parameter": "EiAvQ2hhbm5lbC9BcHBsaWNhdGlvbi9FbmRvcnNlbWVudA==",
"validation_plugin": "vscc",
"version": "3.0.0"
}
],
"failed": false,
"installed_chaincodes": [
{
"label": "asset-transfer",
"package_id": "asset-transfer:8b4c3e8fde8b4d96264aeb2d9b9e22ace299086f41215f74fc844d1e32b1a5fb",
"references": {
"cashchannel": {
"chaincodes": [
{
"name": "asset-transfer",
"version": "3.0.0"
}
]
}
}
}
]
}
```
=> Chaincode Information

roles/console/templates/k8s/console.yml.j2, roles/console/templates/openshift/console.yml.j2
This change involves changes in the product version condition for the Console Jinja2 template under roles for K8 and open shift. This change is done to test the existing collection to run for the hlfsupport offering.
=> Product Version Changes in console templates 

galaxy.yml
PRs were failing because we didn't have a required tag. This repository is deprecated, but we still need to do some final maintenance to get it to **show** as deprecated.
=> Address the build error for required tags.
